SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS anime;
DROP TABLE IF EXISTS Actor;
DROP TABLE IF EXISTS anime_has_actor;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_has_favorite;

SET FOREIGN_KEY_CHECKS=1;